services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongodb:27017/decanaria
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    tty: true
    command: tail -f /dev/null

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: 